services:
    pgsql:
        image: "postgis/postgis:17-3.6-alpine"
        network_mode: "host"
        environment:
            PGPASSWORD: "${DB_PASSWORD:-secret}"
            POSTGRES_DB: "${DB_DATABASE}"
            POSTGRES_USER: "${DB_USERNAME}"
            POSTGRES_PASSWORD: "${DB_PASSWORD:-secret}"
        command: ["postgres", "-c", "listen_addresses=127.0.0.1"]
        volumes:
            - pgsql-data:/var/lib/postgresql/data
        healthcheck:
            test:
                - CMD
                - pg_isready
                - "-q"
                - "-d"
                - "${DB_DATABASE}"
                - "-U"
                - "${DB_USERNAME}"
            retries: 3
            timeout: 5s

    redis:
        image: "redis:alpine"
        network_mode: "host"
        command: ["redis-server", "--bind", "127.0.0.1", "--protected-mode", "yes"]
        volumes:
            - redis-data:/data
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

    mailpit:
        image: "axllent/mailpit:latest"
        network_mode: "host"
        command: ["--listen", "127.0.0.1:8025", "--smtp", "127.0.0.1:1025"]
        healthcheck:
            test:
                - CMD
                - curl
                - "-f"
                - "http://localhost:8025"
            retries: 3
            timeout: 5s

    minio:
        image: "minio/minio:latest"
        network_mode: "host"
        environment:
            MINIO_ROOT_USER: "${MINIO_ROOT_USER:-admin}"
            MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD:-password}"
        volumes:
            - minio-data:/data
        command: 'minio server /data --address "127.0.0.1:9000" --console-address "127.0.0.1:8900"'
        healthcheck:
            test:
                - CMD
                - curl
                - "-f"
                - "http://localhost:9000/minio/health/live"
            retries: 3
            timeout: 5s

volumes:
    pgsql-data:
        driver: local
    redis-data:
        driver: local
    minio-data:
        driver: local
